pipeline{
    agent { node {label 'agent1'}}
    options {
        ansiColor('xterm')
    }
    stages {
        stage ('init') {
            steps {
                sh '''
                   cd roboshop-infra-standard/01-vpc
                   pwd
                   ls -ltr
                   terraform init
                '''
            }
        }
        stage ('plan') {
            steps {
                sh '''
                   cd 01-vpc
                   pwd
                   ls -ltr
                   terraform plan
                '''
            }
        }
    }
}